return {
	-- {
	-- 	"LazyVim/LazyVim",
	-- 	opts = {
	-- 		colorscheme = "catppuccin",
	-- 	},
	-- },
	-- {
	-- 	"catppuccin/nvim",
	-- 	name = "catppuccin",
	-- 	opts = {
	-- 		term_colors = true,
	-- 		transparent_background = false,
	-- 		styles = {
	-- 			comments = {},
	-- 			conditionals = {},
	-- 			loops = {},
	-- 			functions = {},
	-- 			keywords = {},
	-- 			strings = {},
	-- 			variables = {},
	-- 			numbers = {},
	-- 			booleans = {},
	-- 			properties = {},
	-- 			types = {},
	-- 		},
	-- 		color_overrides = {
	-- 			mocha = {
	-- 				base = "#000000",
	-- 				mantle = "#102030",
	-- 				crust = "#50B0C0",
	-- 			},
	-- 		},
	-- 		integrations = {
	-- 			telescope = {
	-- 				enabled = true,
	-- 				style = "nvchad",
	-- 			},
	-- 			dropbar = {
	-- 				enabled = true,
	-- 				color_mode = true,
	-- 			},
	-- 		},
	-- 	},
	-- },
}
